### ISSUE TITLE
Set the project URL to point to the bot

### ISSUE THREAD

**Issue by porglezomp** [a2aaron/mario-epics#18]
In settings, the project URL should be http://twitter.com/mario_epics

**Comment by a2aaron** [comment]
Shouldn't it be https://github.com/a2aaron/mario-epics? I'm looking at the Twitter Apps setting page and it says "Your application's publicly accessible home page, where users can go to download, make use of, or find out more information about your application. This fully-qualified URL is used in the source attribution for tweets created by your application and will be shown in user-facing authorization screens.
(If you don't have a URL yet, just put a placeholder here but remember to change it later.)"

I'm gonna put our GitHub link for now.

**Comment by porglezomp** [comment]
When I say the "project URL" I mean at the top of the GitHub page, not elsewhere.

**Comment by a2aaron** [comment]
done!
